vulnerabilities:
  - id: CVE-2026-24842
    paths:
      - "package-lock.json"
    statement: downstream dependency for tar - waiting for new npm release
    expired_at: 2026-06-01
  - id: CVE-2026-25547
    paths:
      - "package-lock.json"
    statement: downstream dependency for braces-expansion - waiting for new npm release
    expired_at: 2026-06-01
  - id: CVE-2026-0775
    paths:
      - "package-lock.json"
    statement: waiting for new npm release
    expired_at: 2026-06-01
  - id: CVE-2026-26960
    paths:
      - "package-lock.json"
    statement: Can't ditch tar, we will have to wait for a fix.
    expired_at: 2026-03-01
