name: Build
on:
  workflow_call:

jobs:
  create_release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # This causes all history to be fetched, which is required for calculate-version to function

      # using git commit sha for version of action to ensure we have stable version
      - name: Install asdf
        uses: asdf-vm/actions/setup@6a442392015fbbdd8b48696d41e0051b2698b2e4
        with:
          asdf_branch: v0.11.3

      - name: Cache asdf
        uses: actions/cache@v3
        with:
          path: |
            ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
          restore-keys: |
            ${{ runner.os }}-asdf-

      - name: Install asdf dependencies in .tool-versions
        uses: asdf-vm/actions/install@6a442392015fbbdd8b48696d41e0051b2698b2e4
        with:
          asdf_branch: v0.11.3
        env:
          PYTHON_CONFIGURE_OPTS: --enable-shared

      - name: Install python packages
        run: |
          export PATH="/home/runner/.asdf/installs/poetry/1.7.0/bin:$PATH"
          poetry install
